create table if not exists ACCTG_TRANS(
    ACCTG_TRANS_ID String,
    ACCTG_TRANS_TYPE_ID String,
    DESCRIPTION String,
    TRANSACTION_DATE Datetime,
    IS_POSTED String,
    POSTED_DATE Datetime,
    SCHEDULED_POSTING_DATE Datetime,
    GL_JOURNAL_ID String,
    GL_FISCAL_TYPE_ID String,
    VOUCHER_REF String,
    VOUCHER_DATE Datetime,
    GROUP_STATUS_ID String,
    FIXED_ASSET_ID String,
    INVENTORY_ITEM_ID String,
    PHYSICAL_INVENTORY_ID String,
    PARTY_ID String,
    ROLE_TYPE_ID String,
    INVOICE_ID String,
    PAYMENT_ID String,
    FIN_ACCOUNT_TRANS_ID String,
    SHIPMENT_ID String,
    RECEIPT_ID String,
    WORK_EFFORT_ID String,
    THEIR_ACCTG_TRANS_ID String,
    CREATED_DATE Datetime,
    CREATED_BY_USER_LOGIN String,
    LAST_MODIFIED_DATE Datetime,
    LAST_MODIFIED_BY_USER_LOGIN String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);