create table if not exists ACCTG_TRANS_ENTRY(
    ACCTG_TRANS_ID String,
    ACCTG_TRANS_ENTRY_SEQ_ID String,
    ACCTG_TRANS_ENTRY_TYPE_ID String,
    DESCRIPTION String,
    VOUCHER_REF String,
    PARTY_ID String,
    ROLE_TYPE_ID String,
    THEIR_PARTY_ID String,
    PRODUCT_ID String,
    THEIR_PRODUCT_ID String,
    INVENTORY_ITEM_ID String,
    GL_ACCOUNT_TYPE_ID String,
    GL_ACCOUNT_ID String,
    ORGANIZATION_PARTY_ID String,
    AMOUNT Decimal(16,2) ,
    CURRENCY_UOM_ID String,
    ORIG_AMOUNT Decimal(16,2) ,
    ORIG_CURRENCY_UOM_ID String,
    DEBIT_CREDIT_FLAG String,
    DUE_DATE **UNK**,
    GROUP_ID String,
    TAX_ID String,
    RECONCILE_STATUS_ID String,
    SETTLEMENT_TERM_ID String,
    IS_SUMMARY String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);