create table if not exists FIXED_ASSET(
    FIXED_ASSET_ID String,
    FIXED_ASSET_TYPE_ID String,
    PARENT_FIXED_ASSET_ID String,
    INSTANCE_OF_PRODUCT_ID String,
    CLASS_ENUM_ID String,
    PARTY_ID String,
    ROLE_TYPE_ID String,
    FIXED_ASSET_NAME String,
    ACQUIRE_ORDER_ID String,
    ACQUIRE_ORDER_ITEM_SEQ_ID String,
    DATE_ACQUIRED Datetime,
    DATE_LAST_SERVICED Datetime,
    DATE_NEXT_SERVICE Datetime,
    EXPECTED_END_OF_LIFE **UNK**,
    ACTUAL_END_OF_LIFE **UNK**,
    PRODUCTION_CAPACITY Decimal(16,2) ,
    UOM_ID String,
    CALENDAR_ID String,
    SERIAL_NUMBER String,
    LOCATED_AT_FACILITY_ID String,
    LOCATED_AT_LOCATION_SEQ_ID String,
    SALVAGE_VALUE Decimal(16,2) ,
    DEPRECIATION Decimal(16,2) ,
    PURCHASE_COST Decimal(16,2) ,
    PURCHASE_COST_UOM_ID String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);