create table if not exists INVENTORY_ITEM(
    INVENTORY_ITEM_ID String,
    INVENTORY_ITEM_TYPE_ID String,
    PRODUCT_ID String,
    PARTY_ID String,
    OWNER_PARTY_ID String,
    STATUS_ID String,
    DATETIME_RECEIVED Datetime,
    DATETIME_MANUFACTURED Datetime,
    EXPIRE_DATE Datetime,
    FACILITY_ID String,
    CONTAINER_ID String,
    LOT_ID String,
    UOM_ID String,
    BIN_NUMBER String,
    LOCATION_SEQ_ID String,
    COMMENTS String,
    QUANTITY_ON_HAND_TOTAL Decimal(16,2) ,
    AVAILABLE_TO_PROMISE_TOTAL Decimal(16,2) ,
    ACCOUNTING_QUANTITY_TOTAL Decimal(16,2) ,
    QUANTITY_ON_HAND Decimal(16,2) ,
    AVAILABLE_TO_PROMISE Decimal(16,2) ,
    SERIAL_NUMBER String,
    SOFT_IDENTIFIER String,
    ACTIVATION_NUMBER String,
    ACTIVATION_VALID_THRU Datetime,
    UNIT_COST Decimal(16,2) ,
    CURRENCY_UOM_ID String,
    FIXED_ASSET_ID String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);