create table if not exists ORDER_PAYMENT_PREFERENCE(
    ORDER_PAYMENT_PREFERENCE_ID String,
    ORDER_ID String,
    ORDER_ITEM_SEQ_ID String,
    SHIP_GROUP_SEQ_ID String,
    PRODUCT_PRICE_PURPOSE_ID String,
    PAYMENT_METHOD_TYPE_ID String,
    PAYMENT_METHOD_ID String,
    FIN_ACCOUNT_ID String,
    SECURITY_CODE String,
    TRACK2 String,
    PRESENT_FLAG String,
    SWIPED_FLAG String,
    OVERFLOW_FLAG String,
    MAX_AMOUNT Decimal(16,2) ,
    PROCESS_ATTEMPT Decimal(16,2) ,
    BILLING_POSTAL_CODE String,
    MANUAL_AUTH_CODE String,
    MANUAL_REF_NUM String,
    STATUS_ID String,
    NEEDS_NSF_RETRY String,
    CREATED_DATE Datetime,
    CREATED_BY_USER_LOGIN String,
    LAST_MODIFIED_DATE Datetime,
    LAST_MODIFIED_BY_USER_LOGIN String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);