create table if not exists ORDER_ITEM(
    ORDER_ID String,
    ORDER_ITEM_SEQ_ID String,
    EXTERNAL_ID String,
    ORDER_ITEM_TYPE_ID String,
    ORDER_ITEM_GROUP_SEQ_ID String,
    IS_ITEM_GROUP_PRIMARY String,
    FROM_INVENTORY_ITEM_ID String,
    BUDGET_ID String,
    BUDGET_ITEM_SEQ_ID String,
    PRODUCT_ID String,
    SUPPLIER_PRODUCT_ID String,
    PRODUCT_FEATURE_ID String,
    PROD_CATALOG_ID String,
    PRODUCT_CATEGORY_ID String,
    IS_PROMO String,
    QUOTE_ID String,
    QUOTE_ITEM_SEQ_ID String,
    SHOPPING_LIST_ID String,
    SHOPPING_LIST_ITEM_SEQ_ID String,
    SUBSCRIPTION_ID String,
    DEPLOYMENT_ID String,
    QUANTITY Decimal(16,2) ,
    CANCEL_QUANTITY Decimal(16,2) ,
    SELECTED_AMOUNT Decimal(16,2) ,
    UNIT_PRICE Decimal(16,2) ,
    UNIT_LIST_PRICE Decimal(16,2) ,
    UNIT_AVERAGE_COST Decimal(16,2) ,
    UNIT_RECURRING_PRICE Decimal(16,2) ,
    IS_MODIFIED_PRICE String,
    RECURRING_FREQ_UOM_ID String,
    ITEM_DESCRIPTION String,
    COMMENTS String,
    CORRESPONDING_PO_ID String,
    STATUS_ID String,
    SYNC_STATUS_ID String,
    ESTIMATED_SHIP_DATE Datetime,
    ESTIMATED_DELIVERY_DATE Datetime,
    AUTO_CANCEL_DATE Datetime,
    DONT_CANCEL_SET_DATE Datetime,
    DONT_CANCEL_SET_USER_LOGIN String,
    SHIP_BEFORE_DATE Datetime,
    SHIP_AFTER_DATE Datetime,
    CANCEL_BACK_ORDER_DATE Datetime,
    OVERRIDE_GL_ACCOUNT_ID String,
    SALES_OPPORTUNITY_ID String,
    CHANGE_BY_USER_LOGIN_ID String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);