create table if not exists ORDER_ADJUSTMENT(
    ORDER_ADJUSTMENT_ID String,
    ORDER_ADJUSTMENT_TYPE_ID String,
    ORDER_ID String,
    ORDER_ITEM_SEQ_ID String,
    SHIP_GROUP_SEQ_ID String,
    COMMENTS String,
    DESCRIPTION String,
    AMOUNT Decimal(16,2) ,
    RECURRING_AMOUNT Decimal(16,2) ,
    AMOUNT_ALREADY_INCLUDED Decimal(16,2) ,
    PRODUCT_PROMO_ID String,
    PRODUCT_PROMO_RULE_ID String,
    PRODUCT_PROMO_ACTION_SEQ_ID String,
    PRODUCT_FEATURE_ID String,
    CORRESPONDING_PRODUCT_ID String,
    TAX_AUTHORITY_RATE_SEQ_ID String,
    SOURCE_REFERENCE_ID String,
    SOURCE_PERCENTAGE Decimal(16,2) ,
    CUSTOMER_REFERENCE_ID String,
    PRIMARY_GEO_ID String,
    SECONDARY_GEO_ID String,
    EXEMPT_AMOUNT Decimal(16,2) ,
    TAX_AUTH_GEO_ID String,
    TAX_AUTH_PARTY_ID String,
    OVERRIDE_GL_ACCOUNT_ID String,
    INCLUDE_IN_TAX String,
    INCLUDE_IN_SHIPPING String,
    IS_MANUAL String,
    CREATED_DATE Datetime,
    CREATED_BY_USER_LOGIN String,
    LAST_MODIFIED_DATE Datetime,
    LAST_MODIFIED_BY_USER_LOGIN String,
    ORIGINAL_ADJUSTMENT_ID String,
    AMOUNT_PER_QUANTITY Decimal(16,2) ,
    PERCENTAGE **UNK**,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);