create table if not exists PARTY_ACCTG_PREFERENCE(
    PARTY_ID String,
    FISCAL_YEAR_START_MONTH Decimal(16,2) ,
    FISCAL_YEAR_START_DAY Decimal(16,2) ,
    TAX_FORM_ID String,
    COGS_METHOD_ID String,
    BASE_CURRENCY_UOM_ID String,
    INVOICE_SEQ_CUST_METH_ID String,
    INVOICE_ID_PREFIX String,
    LAST_INVOICE_NUMBER Decimal(16,2) ,
    LAST_INVOICE_RESTART_DATE Datetime,
    USE_INVOICE_ID_FOR_RETURNS String,
    QUOTE_SEQ_CUST_METH_ID String,
    QUOTE_ID_PREFIX String,
    LAST_QUOTE_NUMBER Decimal(16,2) ,
    ORDER_SEQ_CUST_METH_ID String,
    ORDER_ID_PREFIX String,
    LAST_ORDER_NUMBER Decimal(16,2) ,
    REFUND_PAYMENT_METHOD_ID String,
    ERROR_GL_JOURNAL_ID String,
    ENABLE_ACCOUNTING String,
    INVOICE_SEQUENCE_ENUM_ID String,
    ORDER_SEQUENCE_ENUM_ID String,
    QUOTE_SEQUENCE_ENUM_ID String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);