create table if not exists PERSON(
    PARTY_ID String,
    SALUTATION String,
    FIRST_NAME String,
    MIDDLE_NAME String,
    LAST_NAME String,
    PERSONAL_TITLE String,
    SUFFIX String,
    NICKNAME String,
    FIRST_NAME_LOCAL String,
    MIDDLE_NAME_LOCAL String,
    LAST_NAME_LOCAL String,
    OTHER_LOCAL String,
    MEMBER_ID String,
    GENDER String,
    BIRTH_DATE **UNK**,
    DECEASED_DATE **UNK**,
    HEIGHT **UNK**,
    WEIGHT **UNK**,
    MOTHERS_MAIDEN_NAME String,
    MARITAL_STATUS String,
    SOCIAL_SECURITY_NUMBER String,
    PASSPORT_NUMBER String,
    PASSPORT_EXPIRE_DATE **UNK**,
    TOTAL_YEARS_WORK_EXPERIENCE **UNK**,
    COMMENTS String,
    EMPLOYMENT_STATUS_ENUM_ID String,
    RESIDENCE_STATUS_ENUM_ID String,
    OCCUPATION String,
    YEARS_WITH_EMPLOYER Decimal(16,2) ,
    MONTHS_WITH_EMPLOYER Decimal(16,2) ,
    EXISTING_CUSTOMER String,
    CARD_ID String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime,
    MARITAL_STATUS_ENUM_ID String) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);