create table if not exists PRODUCT(
    PRODUCT_ID String,
    PRODUCT_TYPE_ID String,
    PRIMARY_PRODUCT_CATEGORY_ID String,
    FACILITY_ID String,
    INTRODUCTION_DATE Datetime,
    RELEASE_DATE Datetime,
    SUPPORT_DISCONTINUATION_DATE Datetime,
    SALES_DISCONTINUATION_DATE Datetime,
    SALES_DISC_WHEN_NOT_AVAIL String,
    INTERNAL_NAME String,
    BRAND_NAME String,
    COMMENTS String,
    PRODUCT_NAME String,
    DESCRIPTION String,
    LONG_DESCRIPTION String,
    PRICE_DETAIL_TEXT String,
    SMALL_IMAGE_URL String,
    MEDIUM_IMAGE_URL String,
    LARGE_IMAGE_URL String,
    DETAIL_IMAGE_URL String,
    ORIGINAL_IMAGE_URL String,
    DETAIL_SCREEN String,
    INVENTORY_MESSAGE String,
    INVENTORY_ITEM_TYPE_ID String,
    REQUIRE_INVENTORY String,
    QUANTITY_UOM_ID String,
    QUANTITY_INCLUDED Decimal(16,2) ,
    PIECES_INCLUDED Decimal(16,2) ,
    REQUIRE_AMOUNT String,
    FIXED_AMOUNT Decimal(16,2) ,
    AMOUNT_UOM_TYPE_ID String,
    WEIGHT_UOM_ID String,
    SHIPPING_WEIGHT Decimal(16,2) ,
    PRODUCT_WEIGHT Decimal(16,2) ,
    HEIGHT_UOM_ID String,
    PRODUCT_HEIGHT Decimal(16,2) ,
    SHIPPING_HEIGHT Decimal(16,2) ,
    WIDTH_UOM_ID String,
    PRODUCT_WIDTH Decimal(16,2) ,
    SHIPPING_WIDTH Decimal(16,2) ,
    DEPTH_UOM_ID String,
    PRODUCT_DEPTH Decimal(16,2) ,
    SHIPPING_DEPTH Decimal(16,2) ,
    DIAMETER_UOM_ID String,
    PRODUCT_DIAMETER Decimal(16,2) ,
    PRODUCT_RATING Decimal(16,2) ,
    RATING_TYPE_ENUM String,
    RETURNABLE String,
    TAXABLE String,
    CHARGE_SHIPPING String,
    AUTO_CREATE_KEYWORDS String,
    INCLUDE_IN_PROMOTIONS String,
    IS_VIRTUAL String,
    IS_VARIANT String,
    VIRTUAL_VARIANT_METHOD_ENUM String,
    ORIGIN_GEO_ID String,
    REQUIREMENT_METHOD_ENUM_ID String,
    BILL_OF_MATERIAL_LEVEL Decimal(16,2) ,
    RESERV_MAX_PERSONS Decimal(16,2) ,
    RESERV2ND_P_P_PERC Decimal(16,2) ,
    RESERV_NTH_P_P_PERC Decimal(16,2) ,
    CONFIG_ID String,
    CREATED_DATE Datetime,
    CREATED_BY_USER_LOGIN String,
    LAST_MODIFIED_DATE Datetime,
    LAST_MODIFIED_BY_USER_LOGIN String,
    IN_SHIPPING_BOX String,
    DEFAULT_SHIPMENT_BOX_TYPE_ID String,
    LOT_ID_FILLED_IN String,
    ORDER_DECIMAL_QUANTITY String,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);