create table if not exists SHIPMENT_COST_ESTIMATE(
    SHIPMENT_COST_ESTIMATE_ID String,
    SHIPMENT_METHOD_TYPE_ID String,
    CARRIER_PARTY_ID String,
    CARRIER_ROLE_TYPE_ID String,
    PRODUCT_STORE_SHIP_METH_ID String,
    PRODUCT_STORE_ID String,
    PARTY_ID String,
    ROLE_TYPE_ID String,
    GEO_ID_TO String,
    GEO_ID_FROM String,
    WEIGHT_BREAK_ID String,
    WEIGHT_UOM_ID String,
    WEIGHT_UNIT_PRICE Decimal(16,2) ,
    QUANTITY_BREAK_ID String,
    QUANTITY_UOM_ID String,
    QUANTITY_UNIT_PRICE Decimal(16,2) ,
    PRICE_BREAK_ID String,
    PRICE_UOM_ID String,
    PRICE_UNIT_PRICE Decimal(16,2) ,
    ORDER_FLAT_PRICE Decimal(16,2) ,
    ORDER_PRICE_PERCENT Decimal(16,2) ,
    ORDER_ITEM_FLAT_PRICE Decimal(16,2) ,
    SHIPPING_PRICE_PERCENT Decimal(16,2) ,
    PRODUCT_FEATURE_GROUP_ID String,
    OVERSIZE_UNIT Decimal(16,2) ,
    OVERSIZE_PRICE Decimal(16,2) ,
    FEATURE_PERCENT Decimal(16,2) ,
    FEATURE_PRICE Decimal(16,2) ,
    LAST_UPDATED_STAMP Datetime,
    LAST_UPDATED_TX_STAMP Datetime,
    CREATED_STAMP Datetime,
    CREATED_TX_STAMP Datetime) engine=MergeTree
partition by toYYYYMMDD(create_time)
primary key (id) order by (id);